### PR TITLE
sign up page with stub pending sign up api

### PR DESCRIPTION
**Pull request by orunto**
This fixes issue #10 

Bootstrapped with create-react-app
Sass for styling
Notiflix for notifications and alerts

### CODE REVIEW

**Comment by devvspaces** [comment]
Hi, add gitignore in the frontend folder to ignore node modules, you pushed it along

**Comment by devvspaces** [comment]
remove the tracked files too, so we dont' merge it

git -rm --cached "node_modules"

**Comment by devvspaces** [comment]
also request me as a reviewer

**Comment by orunto** [comment]
> also request me as a reviewer

Alright

**Comment by orunto** [comment]
> remove the tracked files too, so we dont' merge it
> 
> git -rm --cached "node_modules"

I didn't know I could still make those changes to a pull request

**Comment by devvspaces** [comment]
just work on the same branch and push again, the pr will update with the new commits

**Review by devvspaces — CHANGES_REQUESTED** [review]
Where are there package.json and log files updated in the root folder, pleaes remove them

**Comment by orunto** [comment]
> Where are there package.json and log files updated in the root folder, pleaes remove them

I realized why the node_modules and package.json appeared in root. I'm correcting it now

**Comment by orunto** [comment]
> Where are there package.json and log files updated in the root folder, pleaes remove them

It has been corrected

**Review by devvspaces — APPROVED** [review]

**Pull request merged**
